version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=true
    networks:
      - default
    environment:
      # IMPORTANT NOTE:
      # server name "Docker" should be set in PhpStorm Settings -> PHP -> Servers -> Name = Docker
      # Host => 127.0.0.1 Port => 888 Debugger => Xdebug
      # Add checked => Use path mapping
      # Add absolute path on server in project files => /var/www
      # Follow instruction picture in this catalog -> PhpStorm-XdebugSettings.png
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ../src/:/var/www/
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on: 
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ../src:/var/www:rw
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - php-fpm

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - default
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      APP_ENV: dev
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha

networks:
    default:

volumes:
  db_data:
